Wheater App
NataJenkins/WeatherAppJs pull request #2
Opened 2021-04-22 19:37 UTC by NataJenkins

Wheater app created using javascript where data is fetched through an api

2021-04-23 00:21 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello  Nat Macias Ortiz** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] In your package.json file, add the next:
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
```
- [x]  changes the page appearance based on the received data
- [ ]  It should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit.
- [x] In your README file, explain how to run this project.
- [ ] Use arrow functions whenever possible

#### OPTIONAL

- Please, next time don't close a pull request before approval
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-04-23 00:21 UTC, andresporras3423 commented on src/app/index.js
> +async function fetchWeather() {
use arrow functions whenever possible

2021-04-27 22:00 UTC, uche-inyama requested changes
## Changes Required

### Hi @NataJenkins :wave: 

After following the instructions on your readme file, I could not start the application locally on my machine. I got an error, I will leave a gif below for clarifications.

![Peek 2021-04-27 22-42](https://user-images.githubusercontent.com/46329537/116316980-a2a60400-a7aa-11eb-9038-796438f8277a.gif)


Also, there is no **live demo link** on your readme file.

* [ ] I ran the application using vscode's live server, the form was not working and one of the fields **country code** you provided is not in the project requirements. Here is a gif.

![error](https://user-images.githubusercontent.com/46329537/116317877-dc2b3f00-a7ab-11eb-828e-4e14491923ec.gif)


* [ ] Also the feedback you got from your last review about using arrow functions hasn't been  
implemented.

#### Make these changes then submit another form for a code review.


### Happy coding :man_technologist: 

#### ``` Uchechukwu Henry Inyama ```

2021-04-28 18:19 UTC, NataJenkins commented
the application is working fine for me. you can reach me if you re having any troubles

2021-04-28 19:02 UTC, arslanbisharat requested changes
# Changes Requested 💀 

Thank you for submitting the PR. 

As requested in previous [Code Reviews](https://github.com/NataJenkins/WeatherAppJs/pull/2#pullrequestreview-646396522) your project cannot be run. Please reach out to FT CRs for a 1:1 call to resolve your issue. 

Best, 
Arslan Bisharat
slack:arslanbisharat 🤙

2021-04-28 20:47 UTC, arslanbisharat requested changes
# Changes Requested 💀 

Thank you for submitting the PR. 

As requested in previous [Code Reviews](https://github.com/NataJenkins/WeatherAppJs/pull/2#pullrequestreview-646396522) your project cannot be run. Please reach out to FT CRs for a 1:1 call to resolve your issue. 

Please don't waste your Code Reviews.
<img width="759" alt="1" src="https://user-images.githubusercontent.com/58504655/116470373-c772a800-a88c-11eb-83b3-1fa18acd20b6.PNG">



Best, 
Arslan Bisharat.
slack:arslanbisharat 🤙

2021-04-28 21:44 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @NataJenkins :wave:

_I must commend your efforts so far in this project. Most of the features seem to be working._

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] As mentioned by @uche-inyama, you need to deploy your app and add the live demo link to the Readme.
- [ ] Also, you need to completely use the ES6 features. For instance, use `import` instead of `require`, as observed in `src/app/index.js`. 

* * *
**Please make the required changes and submit another review request when you are done.**

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-28 21:44 UTC, teekaytech commented on src/app/store.js
> +    }
**[ OPTIONAL ]**

- You might want to change the long if-else statement in `src/app/store.js` to a switch/case statement.

2021-04-28 21:44 UTC, teekaytech commented on src/app/ui.js
> +    }
**[ OPTIONAL ]**

- You can also change this to a switch/case statement.

2021-04-29 00:04 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED✔✔✔**

Great project👏👏
You can merge and move on👍✔

Happy coding💻💻💻

2021-07-13 22:22 UTC, merged